- name: copy file
  hosts: client1
  become: yes
  tasks:
          - name: touch file1
            copy:
                    dest: /home/redhat/mkdir.yml
                    content: "Hello World !!!!"

