- name: add users
  hosts: all
  become: yes
  vars:
    packages:
      - vim
      - ftp
  tasks :
          # - name: Ajout de VIM et FTP
          #   yum: 
          #     name: "{{ packages }}" 
          #     state: present

         - user:
                  name: "{{ item }}"
                  state: present
           with_items:
                          - user1100
                          - user1200
                          - user1300
           when: '"prod1" in group_names'

                      
