- name: when host in group
  hosts: all
  become: yes
  gather_facts: no
  tasks:
          - name: install vim in cl1
            yum:
                    name: vim
                    state: present
            when: '"prod1" in group_names'
          - name: install httpd in cl2
            yum:
                    name: httpd
                    state: present
            when: '"prod2" in group_names'

